theme: jekyll-theme-minimal
title: Pauline Bonnet
description: Passionate about climate physics and science outreach. I lead initiatives that bridge research and practical action to address the environmental crisis ! Life's a dream, go for it!
logo: png/photo_Pauline.png

