theme: jekyll-theme-minimal
title: Pauline Bonnet
description: Are your curious about glaciology, atmospheric physics, or science & art communication ? Don't hesitate to give me a shout :)
logo: png/photo_Pauline.png

