theme: jekyll-theme-minimal
title: Pauline Bonnet
description: I am passionate about phenomena related to polar glaciers, and atmospheric physics, and powerful tools to study these physical processes such as numerical modelling and machine learning.
logo: png/photo_Pauline.png

